### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by developer239** [wahengchang/react-redux-boilerplate#7]
How would you handle importing images?

**Comment by wahengchang** [comment]
Do you mean copying image to public, and using in html tag ?

I usually put image in `public directory`, which is support by express: [read more](https://expressjs.com/en/starter/static-files.html)

#### such as
```
<img src="/public/logo.png" />
```

**Comment by developer239** [comment]
The correct way in react would be importing static assets directly inside components using `import` or `require`. I was trying to make ssr hot reloading work with express but it is currently not possible because of images. The only right way how to make ssr work with hot reloading is by using webpack.

**Comment by wahengchang** [comment]
I am sorry @developer239, it may take me more time to understand that, to commit a new version to fit the requirement. Because we use to upload images to cdn, that is why I did not encounter this situation.

**Comment by developer239** [comment]
Yea cool :) I am working on boilerplate with ssr right now I might post an example once I am done. Hopefully by the end of the weekend.

**Comment by ghost** [comment]
Hey @developer239 
Could you please have a look at https://github.com/wahengchang/react-redux-boilerplate/issues/8 if you are working on a version of this as the foundation of your boilerplate
