### ISSUE TITLE
Routing doesn't seem to work with Link

### ISSUE THREAD

**Issue by ghost** [wahengchang/react-redux-boilerplate#8]
I was trying to use `Link from  'react-router-dom'` but the routing doesn't work

`hello.js`
```
import { Link } from 'react-router-dom'
import style from './Hello.css'

const Hello = ({ onClick, message }) => {
  return (
    <div>
      <Link to="/preload"><h1 className={classNames(style['title'])}>{ message }</h1></Link>
      <button onClick={onClick}>Click</button>
    </div>
  )
}
```
But the transition just doesn't happen

Could you please help me? Also I was looking at using `react-router-redux` with `history` but the updated code wasn't working although I followed the same tutorials as per here https://github.com/reactjs/react-router-redux

Thanks,
Rahul Basu

**Comment by ghost** [comment]
Found the solution!

In `clientRender.js ` please change
```
   <StaticRouter location={window.location.pathname} context={{}}>
      <Switch>
        {
          matchConfig.map((route, index) => <Route key={`route${index}`} {...route} />)
        }
      </Switch>
    </StaticRouter>
```
to 
```
    <BrowserRouter>
        <Switch>
          {
            matchConfig.map((route, index) => <Route key={`route${index}`} {...route} />)
          }
        </Switch>
    </BrowserRouter>
```

And you could commit to the repo once changed.

Otherwise the Router just doesn't work on the client side as static router doesn't change the DOM internally

Thanks,
Rahul

**Comment by wahengchang** [comment]
commit #ecfdf085bf2c94f1d91ceda8833a06d77b812ac2

**Comment by wahengchang** [comment]
It is a mistake, `StaticRouter` is for server side rendering, `BrowserRout` should be used in clicent rendering
