### ISSUE TITLE
HMR + auto reload

### ISSUE THREAD

**Issue by rszhd** [wahengchang/react-redux-boilerplate#9]
Hi, i tried to understand this boilerplate. I do install and run using dev mode and make a few change to the file. Its working fine but am i suppose to manually refresh the browser everytime i do a js/css/html code change? HMR alone will only update the component where code is changed, but it doesnt reload automatically right?

**Comment by wahengchang** [comment]
@prettyodd , it seem that HMR has this feature.
```
http://matthewlehner.net/react-hot-module-replacement-with-webpack/
```

it will be great if you can contribute this dev feature and send a PR to make this repo better :)
